version: 2015.1.{build}

install:
  - cinst stylecop

platform: Any CPU

configuration: Release

build:
  project: Source/UsageStats.sln

artifacts:
  - path: Output
    name: UsageStats-$(APPVEYOR_BUILD_VERSION)
    type: zip
